"""empty message

Revision ID: ce93e8c3219b
Revises: 
Create Date: 2022-02-05 15:02:54.225181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce93e8c3219b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user', sa.Column('pfp', sa.String(length=150), nullable=True))
    op.add_column('user', sa.Column('bio', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'bio')
    op.drop_column('user', 'pfp')
    op.drop_column('user', 'date')
    # ### end Alembic commands ###
